### ISSUE TITLE
Wall and roof jump does not detect on foot area

### ISSUE THREAD

**Issue by nic08** [Ev01/PogoArena#13]
Possible fix (yucy): Make a kinematic body to detect the normal
It happens because area2D's do not call _integrate_forces()

**Comment by Ev01** [comment]
I will try kinematic body fix.

**Comment by Ev01** [comment]
This is fixed using a kinematic body to detect normals. The kinematic body detects wall collisions on collision_layer 2. This means all walls have to be added to collision layer 2.
